/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_power (XDR *xdrs, power *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->base))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->exponente))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_point (XDR *xdrs, point *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vect (XDR *xdrs, vect *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->vect_val, (u_int *) &objp->vect_len, 32,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_matrix (XDR *xdrs, matrix *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->matrix_val, (u_int *) &objp->matrix_len, 32,
		sizeof (vect), (xdrproc_t) xdr_vect))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_matrixv (XDR *xdrs, matrixv *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->matrixv_val, (u_int *) &objp->matrixv_len, 36,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_password (XDR *xdrs, password *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 32))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sumar_1_argument (XDR *xdrs, sumar_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_restar_1_argument (XDR *xdrs, restar_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicar_1_argument (XDR *xdrs, multiplicar_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dividir_1_argument (XDR *xdrs, dividir_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_transladar_1_argument (XDR *xdrs, transladar_1_argument *objp)
{
	 if (!xdr_point (xdrs, &objp->p))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_escalar_1_argument (XDR *xdrs, escalar_1_argument *objp)
{
	 if (!xdr_point (xdrs, &objp->p))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sumarvectores_1_argument (XDR *xdrs, sumarvectores_1_argument *objp)
{
	 if (!xdr_vect (xdrs, &objp->v1))
		 return FALSE;
	 if (!xdr_vect (xdrs, &objp->v2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_restarvectores_1_argument (XDR *xdrs, restarvectores_1_argument *objp)
{
	 if (!xdr_vect (xdrs, &objp->v1))
		 return FALSE;
	 if (!xdr_vect (xdrs, &objp->v2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicarvectores_1_argument (XDR *xdrs, multiplicarvectores_1_argument *objp)
{
	 if (!xdr_vect (xdrs, &objp->v1))
		 return FALSE;
	 if (!xdr_vect (xdrs, &objp->v2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dividirvectores_1_argument (XDR *xdrs, dividirvectores_1_argument *objp)
{
	 if (!xdr_vect (xdrs, &objp->v1))
		 return FALSE;
	 if (!xdr_vect (xdrs, &objp->v2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sumarmatrices_1_argument (XDR *xdrs, sumarmatrices_1_argument *objp)
{
	 if (!xdr_matrix (xdrs, &objp->m1))
		 return FALSE;
	 if (!xdr_matrix (xdrs, &objp->m2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_restarmatrices_1_argument (XDR *xdrs, restarmatrices_1_argument *objp)
{
	 if (!xdr_matrix (xdrs, &objp->m1))
		 return FALSE;
	 if (!xdr_matrix (xdrs, &objp->m2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicarmatrices_1_argument (XDR *xdrs, multiplicarmatrices_1_argument *objp)
{
	 if (!xdr_matrix (xdrs, &objp->m1))
		 return FALSE;
	 if (!xdr_matrix (xdrs, &objp->m2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sumarmatricesv_1_argument (XDR *xdrs, sumarmatricesv_1_argument *objp)
{
	 if (!xdr_matrixv (xdrs, &objp->m1))
		 return FALSE;
	 if (!xdr_matrixv (xdrs, &objp->m2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_restarmatricesv_1_argument (XDR *xdrs, restarmatricesv_1_argument *objp)
{
	 if (!xdr_matrixv (xdrs, &objp->m1))
		 return FALSE;
	 if (!xdr_matrixv (xdrs, &objp->m2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicarmatricesv_1_argument (XDR *xdrs, multiplicarmatricesv_1_argument *objp)
{
	 if (!xdr_matrixv (xdrs, &objp->m1))
		 return FALSE;
	 if (!xdr_matrixv (xdrs, &objp->m2))
		 return FALSE;
	return TRUE;
}
