/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calculadora.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
sumar_1(int a, int b,  CLIENT *clnt)
{
	sumar_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.a = a;
	arg.b = b;
	if (clnt_call (clnt, sumar, (xdrproc_t) xdr_sumar_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
restar_1(int a, int b,  CLIENT *clnt)
{
	restar_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.a = a;
	arg.b = b;
	if (clnt_call (clnt, restar, (xdrproc_t) xdr_restar_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
multiplicar_1(int a, int b,  CLIENT *clnt)
{
	multiplicar_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.a = a;
	arg.b = b;
	if (clnt_call (clnt, multiplicar, (xdrproc_t) xdr_multiplicar_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
dividir_1(int a, int b,  CLIENT *clnt)
{
	dividir_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.a = a;
	arg.b = b;
	if (clnt_call (clnt, dividir, (xdrproc_t) xdr_dividir_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
potencia_1(int a, int b,  CLIENT *clnt)
{
	potencia_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.a = a;
	arg.b = b;
	if (clnt_call (clnt, potencia, (xdrproc_t) xdr_potencia_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

double *
raizcuadrada_1(double a,  CLIENT *clnt)
{
	static double clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, raizcuadrada,
		(xdrproc_t) xdr_double, (caddr_t) &a,
		(xdrproc_t) xdr_double, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

point *
transladar_1(point p, double x, double y, double z,  CLIENT *clnt)
{
	transladar_1_argument arg;
	static point clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.p = p;
	arg.x = x;
	arg.y = y;
	arg.z = z;
	if (clnt_call (clnt, transladar, (xdrproc_t) xdr_transladar_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_point, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

point *
escalar_1(point p, double x, double y, double z,  CLIENT *clnt)
{
	escalar_1_argument arg;
	static point clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.p = p;
	arg.x = x;
	arg.y = y;
	arg.z = z;
	if (clnt_call (clnt, escalar, (xdrproc_t) xdr_escalar_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_point, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

vect *
sumarvectores_1(vect v1, vect v2,  CLIENT *clnt)
{
	sumarvectores_1_argument arg;
	static vect clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.v1 = v1;
	arg.v2 = v2;
	if (clnt_call (clnt, sumarVectores, (xdrproc_t) xdr_sumarvectores_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_vect, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

vect *
restarvectores_1(vect v1, vect v2,  CLIENT *clnt)
{
	restarvectores_1_argument arg;
	static vect clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.v1 = v1;
	arg.v2 = v2;
	if (clnt_call (clnt, restarVectores, (xdrproc_t) xdr_restarvectores_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_vect, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

vect *
multiplicarvectores_1(vect v1, vect v2,  CLIENT *clnt)
{
	multiplicarvectores_1_argument arg;
	static vect clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.v1 = v1;
	arg.v2 = v2;
	if (clnt_call (clnt, multiplicarVectores, (xdrproc_t) xdr_multiplicarvectores_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_vect, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

vect *
dividirvectores_1(vect v1, vect v2,  CLIENT *clnt)
{
	dividirvectores_1_argument arg;
	static vect clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.v1 = v1;
	arg.v2 = v2;
	if (clnt_call (clnt, dividirVectores, (xdrproc_t) xdr_dividirvectores_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_vect, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

char **
cifrar_1(char *password,  CLIENT *clnt)
{
	static char *clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, cifrar,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &password,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

char **
descifrar_1(char *password,  CLIENT *clnt)
{
	static char *clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, descifrar,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &password,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
