/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CIFRADOR_H_RPCGEN
#define _CIFRADOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *password;

#define CIFRADORPROG 0x20000001
#define CIFRADORVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define cifrarfinal 1
extern  char ** cifrarfinal_1(char *, CLIENT *);
extern  char ** cifrarfinal_1_svc(char *, struct svc_req *);
#define descifrarfinal 2
extern  char ** descifrarfinal_1(char *, CLIENT *);
extern  char ** descifrarfinal_1_svc(char *, struct svc_req *);
extern int cifradorprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define cifrarfinal 1
extern  char ** cifrarfinal_1();
extern  char ** cifrarfinal_1_svc();
#define descifrarfinal 2
extern  char ** descifrarfinal_1();
extern  char ** descifrarfinal_1_svc();
extern int cifradorprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_password (XDR *, password*);

#else /* K&R C */
extern bool_t xdr_password ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CIFRADOR_H_RPCGEN */
