/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cifrador.h"

bool_t
xdr_password (XDR *xdrs, password *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 32))
		 return FALSE;
	return TRUE;
}
