/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include "dir.h"


void operacionesprog_1(char *host, int a, char operator, int b) {
    CLIENT *clnt;
	#ifndef	DEBUG
        clnt = clnt_create (host, OPERACIONESPROG, OPERACIONESVER, "udp");
        if (clnt == NULL) {
            clnt_pcreateerror (host);
            exit (1);
        }
    #endif	/* DEBUG */

	int *resultado;
    switch (operator) {
        case '+':
            resultado = sumar_1(a, b, clnt);
            break;
        case '-':
            resultado = restar_1(a, b, clnt);
            break;
        case 'x':
            resultado = multiplicar_1(a, b, clnt);
            break;
        case '/':
            resultado = dividir_1(a, b, clnt);
            break;
    }

    printf("%d %c %d = %d\n", a, operator, b, *resultado);

    #ifndef	DEBUG
        clnt_destroy (clnt);
    #endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
    if (argc < 5) {
        printf("usage: %s server_host first_operand operator second_operand\n", argv[0]);
        exit(1);
    }

    char operator = argv[3][0];

    if (operator != '+' && operator != '-' && operator != 'x' && operator != '/') {
        printf("usage: %s server_host first_operand operator second_operand\n", argv[0]);
        exit(1);
    }

    char* host = argv[1];
    int a = atoi(argv[2]);
    int b = atoi(argv[4]);

    operacionesprog_1 (host, a, operator, b);
    exit (0);
}
