/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"

int *
sumar_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;

	result = arg1 + arg2;

	return &result;
}

int *
restar_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;

    result = arg1 - arg2;

	return &result;
}

int *
multiplicar_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;

    result = arg1 * arg2;

    return &result;
}

int *
dividir_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;

    result = arg1 / arg2;

	return &result;
}
