#
# Autogenerated by Thrift Compiler (0.13.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'vectores_types'

module Vectores
  class Client
    include ::Thrift::Client

    def ping()
      send_ping()
      recv_ping()
    end

    def send_ping()
      send_message('ping', Ping_args)
    end

    def recv_ping()
      result = receive_message(Ping_result)
      return
    end

    def sumarVectores(v1, v2)
      send_sumarVectores(v1, v2)
      return recv_sumarVectores()
    end

    def send_sumarVectores(v1, v2)
      send_message('sumarVectores', SumarVectores_args, :v1 => v1, :v2 => v2)
    end

    def recv_sumarVectores()
      result = receive_message(SumarVectores_result)
      return result.success unless result.success.nil?
      raise result.io unless result.io.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'sumarVectores failed: unknown result')
    end

    def restarVectores(v1, v2)
      send_restarVectores(v1, v2)
      return recv_restarVectores()
    end

    def send_restarVectores(v1, v2)
      send_message('restarVectores', RestarVectores_args, :v1 => v1, :v2 => v2)
    end

    def recv_restarVectores()
      result = receive_message(RestarVectores_result)
      return result.success unless result.success.nil?
      raise result.io unless result.io.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'restarVectores failed: unknown result')
    end

    def multiplicarVectores(v1, v2)
      send_multiplicarVectores(v1, v2)
      return recv_multiplicarVectores()
    end

    def send_multiplicarVectores(v1, v2)
      send_message('multiplicarVectores', MultiplicarVectores_args, :v1 => v1, :v2 => v2)
    end

    def recv_multiplicarVectores()
      result = receive_message(MultiplicarVectores_result)
      return result.success unless result.success.nil?
      raise result.io unless result.io.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'multiplicarVectores failed: unknown result')
    end

    def dividirVectores(v1, v2)
      send_dividirVectores(v1, v2)
      return recv_dividirVectores()
    end

    def send_dividirVectores(v1, v2)
      send_message('dividirVectores', DividirVectores_args, :v1 => v1, :v2 => v2)
    end

    def recv_dividirVectores()
      result = receive_message(DividirVectores_result)
      return result.success unless result.success.nil?
      raise result.io unless result.io.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'dividirVectores failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_ping(seqid, iprot, oprot)
      args = read_args(iprot, Ping_args)
      result = Ping_result.new()
      @handler.ping()
      write_result(result, oprot, 'ping', seqid)
    end

    def process_sumarVectores(seqid, iprot, oprot)
      args = read_args(iprot, SumarVectores_args)
      result = SumarVectores_result.new()
      begin
        result.success = @handler.sumarVectores(args.v1, args.v2)
      rescue ::InvalidOperation => io
        result.io = io
      end
      write_result(result, oprot, 'sumarVectores', seqid)
    end

    def process_restarVectores(seqid, iprot, oprot)
      args = read_args(iprot, RestarVectores_args)
      result = RestarVectores_result.new()
      begin
        result.success = @handler.restarVectores(args.v1, args.v2)
      rescue ::InvalidOperation => io
        result.io = io
      end
      write_result(result, oprot, 'restarVectores', seqid)
    end

    def process_multiplicarVectores(seqid, iprot, oprot)
      args = read_args(iprot, MultiplicarVectores_args)
      result = MultiplicarVectores_result.new()
      begin
        result.success = @handler.multiplicarVectores(args.v1, args.v2)
      rescue ::InvalidOperation => io
        result.io = io
      end
      write_result(result, oprot, 'multiplicarVectores', seqid)
    end

    def process_dividirVectores(seqid, iprot, oprot)
      args = read_args(iprot, DividirVectores_args)
      result = DividirVectores_result.new()
      begin
        result.success = @handler.dividirVectores(args.v1, args.v2)
      rescue ::InvalidOperation => io
        result.io = io
      end
      write_result(result, oprot, 'dividirVectores', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class Ping_args
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Ping_result
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class SumarVectores_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    V1 = 1
    V2 = 2

    FIELDS = {
      V1 => {:type => ::Thrift::Types::LIST, :name => 'v1', :element => {:type => ::Thrift::Types::DOUBLE}},
      V2 => {:type => ::Thrift::Types::LIST, :name => 'v2', :element => {:type => ::Thrift::Types::DOUBLE}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class SumarVectores_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0
    IO = 1

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::DOUBLE}},
      IO => {:type => ::Thrift::Types::STRUCT, :name => 'io', :class => ::InvalidOperation}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class RestarVectores_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    V1 = 1
    V2 = 2

    FIELDS = {
      V1 => {:type => ::Thrift::Types::LIST, :name => 'v1', :element => {:type => ::Thrift::Types::DOUBLE}},
      V2 => {:type => ::Thrift::Types::LIST, :name => 'v2', :element => {:type => ::Thrift::Types::DOUBLE}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class RestarVectores_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0
    IO = 1

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::DOUBLE}},
      IO => {:type => ::Thrift::Types::STRUCT, :name => 'io', :class => ::InvalidOperation}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class MultiplicarVectores_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    V1 = 1
    V2 = 2

    FIELDS = {
      V1 => {:type => ::Thrift::Types::LIST, :name => 'v1', :element => {:type => ::Thrift::Types::DOUBLE}},
      V2 => {:type => ::Thrift::Types::LIST, :name => 'v2', :element => {:type => ::Thrift::Types::DOUBLE}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class MultiplicarVectores_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0
    IO = 1

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::DOUBLE}},
      IO => {:type => ::Thrift::Types::STRUCT, :name => 'io', :class => ::InvalidOperation}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class DividirVectores_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    V1 = 1
    V2 = 2

    FIELDS = {
      V1 => {:type => ::Thrift::Types::LIST, :name => 'v1', :element => {:type => ::Thrift::Types::DOUBLE}},
      V2 => {:type => ::Thrift::Types::LIST, :name => 'v2', :element => {:type => ::Thrift::Types::DOUBLE}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class DividirVectores_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0
    IO = 1

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::DOUBLE}},
      IO => {:type => ::Thrift::Types::STRUCT, :name => 'io', :class => ::InvalidOperation}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

